### ISSUE TITLE
website "bypass" button doesn't seem to work

### ISSUE THREAD

**Issue by Oaklight** [nilsstreedain/duo-bypass#5]
As title.

**Comment by nilsstreedain** [comment]
> As title.

When pasting the URL in and select bypass, does a QR code not appear to the right of the button? Could you describe the behavior of the site along with providing detail about what OS and browser you're issuing? Thanks!

**Comment by nilsstreedain** [comment]
I improved the visual action of the button to make it more clear it is a useable button, not sure if that was the issue but I look forward to hearing more detail about the issue.

**Comment by Oaklight** [comment]
Not sure why but my reply disappeared... anyway, I just reloaded the website, and the button is not clickable: when the cursor moved on the button, there is nothing changed. Try to select, no change. Select and press "enter"; the button has a black edge around it. But nothing seemed to be submitted, and the website has no change of content.

**Comment by nilsstreedain** [comment]
Could you let me know what operating system and browser you're using?

**Comment by Oaklight** [comment]
OS: Deepin 20.7.1
Browser: Vivaldi 5.5.2805.38-1

**Comment by nilsstreedain** [comment]
I was able to test that the site was working using the Vivaldi browser on Mac, unfortunately I don't currently have a linux machine to test the OS with. Though the site worked on Vivaldi, it appears there were some minor features not supported by the browser causing some display issues. Could you try with another browser?

**Comment by Oaklight** [comment]
I tried another Chromium-based browser, the button is now clickable, but nothing was submitted nor QR code showed up.

**Comment by nilsstreedain** [comment]
I'll keep digging into the issue and try to throw up a linux VM. If you are unable to get the site working, there is a [script](https://github.com/nilsstreedain/duo-bypass/tree/main/script) that can be downloaded and run locally if you would still like to access the tool while I work out this issue with the site.

**Comment by Oaklight** [comment]
Thanks, I was able to set this up last night in another way. But I'd like to see your website working! Please keep up the good work!

**Comment by nilsstreedain** [comment]
After testing with the browser version in a VM, I was unable to replicate the issue.
